---

- name: install apache
  apt:
    name: apache2
    state: latest

- name: install postgresql
  apt:
    name: postgresql
    state: latest

- name: install php
  apt:
    name:
      - php
      - libapache2-mod-php
      - php-mcrypt
      - php-mysql
      - php-pgsql 
    state: latest

- name: apache php config
  lineinfile:
    path: /etc/apache2/mods-enabled/dir.conf
    regexp: '^	DirectoryIndex index.html index.cgi index.pl index.php index.xhtml index.htm'
    line: '	DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm'

- name: remove index.html in apache
  file:
    path: /var/www/html/index.html
    state: absent

- name: restart apache
  service:
    name: apache2
    state: restarted
- block:
    - name: create db
      postgresql_db: 
        name: "{{ db_name }}"

    - name: create db user
      postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        expires: infinity

    - name: grant access to db
      postgresql_privs:
        db: "{{ db_name }}"
        role: "{{ db_user }}"
        objs: ALL_IN_SCHEMA
        privs: SELECT,INSERT,UPDATE,DELETE
  become: yes
  become_user: postgres

- name: donwload wordpress
  unarchive:
    src: "{{ wp_link }}"
    dest: /var/www/html/
    remote_src: yes

- name: change wordpess directory
  shell: mv /var/www/html/wordpress/* /var/www/html

- name: delete empty wordpress directory
  file:
    path: /var/www/html/wordpress
    state: absent

- name: download PG4WP
  unarchive:
    src: "{{ pg4wp_link }}"
    dest: /var/www/html/
    remote_src: yes

- name: copy PG4WP
  shell: mv /var/www/html/postgresql-for-wordpress-wordpress4-compat/pg4wp /var/www/html/wp-content/ 

- name: remove empty PG4WP directory
  file:
    path: /var/www/html/postgresql-for-wordpress-wordpress4-compat
    state: absent

- name: copy db.php
  copy:
    src: /var/www/html/wp-content/pg4wp/db.php
    dest: /var/www/html/wp-content/db.php
    remote_src: yes

- name: setting wp config
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php

